enum Capability {
  audioGeneration,
  batchAPI,
  caching,
  codeExecution,
  computerUse,
  fileSearch,
  flexInference,
  functionCalling,
  groundingWithGoogleMaps,
  imageGeneration,
  liveAPI,
  priorityInference,
  searchGrounding,
  structuredOutputs,
  thinking,
  urlContext,
}
